package Roulett;

public enum Splitting {
    GREEN, RED, BLACk, EVEN, ODD, FIRST_18, SECOND_18, ORPHANS, BIG_SERIES, SMALL_SERIES, FIRST_12, SECOND_12, THIRD_12,
    ZERO_NEIGHBORS, FIRST_COLLUM, SECOND_COLLUM, THIRD_COLLUM


}
